; PlatformIO Project Configuration File
; Target: ESP32-S3-WROOM-1-N16R8 (16 MB Flash QIO, 8 MB PSRAM Octal/OPI)
; Vai tro: Firmware dieu khien xe Mecanum, nhan lenh UDP 1 ky tu tu Android app.

[env:esp32-s3-wroom-1-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Khop dung phan cung N16R8 ---
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
; PSRAM 8 MB kieu Octal (OPI)
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
upload_speed = 921600